version: '3.5'

services:
  rabbit:
    container_name: rabbit
    image: rabbitmq:3.7-management
    hostname: "rabbit"
    ports:
      - 15672:15672
      - 5672:5672
    labels:
      NAME: "rabbitmq"
    volumes:
      - ./docker/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./docker/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
      - ./docker/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
      - ./docker/rabbitmq/.erlang.cookie:/var/lib/rabbitmq/mnesia/.erlang.cookie
      - ./.docker/rabbitmq/db:/var/lib/rabbitmq/mnesia/rabbit@rabbit
      - ./.docker/rabbitmq/log:/var/log/rabbitmq/
    networks:
      - backend

  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: "biasuncoverer"
    volumes:
      - ./.docker/mongodb/db:/var/micro-data/mongodb/data/db
    networks:
      - backend

  mongo_seed:
    container_name: mongo_seed
    build: ./docker/mongodb_seed
    environment:
      MONGO_INITDB_DATABASE: "biasuncoverer"
    networks:
      - backend
    depends_on:
      - mongo

networks:
  backend:
    name: backend
    driver: bridge