version: '3'
services:

  rabbit1:
    image: "rabbitmq:3.7-management"
    hostname: "rabbit1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq1"
    volumes:
      - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"
    networks:
      - backend

    mysql:
      image: mysql:8
      container_name: sf4_mysql
      volumes:
        - .docker/data/db:/var/lib/mysql
      command:
        - "--default-authentication-plugin=mysql_native_password"
        - "--lower_case_table_names=1"
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: sf4
        MYSQL_USER: sf4
        MYSQL_PASSWORD: sf4
      networks:
        - backend

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: sf4_phpmyadmin
      environment:
        PMA_HOST: mysql
        PMA_PORT: 3306
      ports:
        - 8083:80
      links:
        - mysql
      networks:
        - backend

networks:
  backend